'use client';
import dynamic from 'next/dynamic';
import Image from 'next/image';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowUpRight,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,RotateCcw,LocateFixed,Map,Pause,Play,X,List,Move,CornerDownLeft} from 'lucide-react';
import {projects,timeline,exhibits} from '@/lib/data';
import type {FieldCommand} from './FieldScene';
import type {Point} from '@/lib/field-physics';
const Scene=dynamic(()=>import('./FieldScene'),{ssr:false,loading:()=> <div className="field-loading"><span>Loading stadium…</span></div>});
type Panel=number|'projects'|'about'|null;
export function FieldPortfolio({children}:{children:ReactNode}){
  const [panel,setPanel]=useState<Panel>(null),[reading,setReading]=useState(false),[follow,setFollow]=useState(false),[motion,setMotion]=useState(true),[running,setRunning]=useState(false),[nearest,setNearest]=useState<number|null>(null),[score,setScore]=useState(0),[ready,setReady]=useState(false);
  const [command,setCommand]=useState<FieldCommand>({id:0,type:'reset'});
  const input=useRef<Point>({x:0,z:0}),dialog=useRef<HTMLDialogElement>(null);
  function openProject(index:number){setPanel(index===9?'about':index);setRunning(false);}
  function toggleReading(){setReading(v=>!v);setPanel(null);setScore(0);setNearest(null);setReady(false);send('reset');}
  function send(type:FieldCommand['type']){setCommand(v=>({id:v.id+1,type}));}
  useEffect(()=>{const el=dialog.current;if(!el)return;if(panel!==null&&!el.open)el.showModal();else if(panel===null&&el.open)el.close();el.scrollTop=0;},[panel]);
  const project=typeof panel==='number'?projects[panel]:null;
  return <>
    <div className={`portfolio-app ${reading?'is-reading':''}`}>
      <header className="field-header"><a href="#top" className="field-brand" onClick={()=>{if(reading)toggleReading();setPanel(null);}}><span className="brand-mark">E<span>M</span></span><span>Ethan Moon<small>Software engineer & researcher</small></span></a><nav aria-label="Main navigation"><button onClick={()=>setPanel('projects')}>Projects <span>09</span></button><button onClick={()=>setPanel('about')}>About</button><a href="/Ethan_Moon_Resume.pdf" target="_blank" rel="noreferrer">Résumé <ArrowUpRight size={14}/></a><button className="view-toggle" aria-label={reading?'Switch to 3D view':'Switch to List view'} onClick={toggleReading}><List size={14}/>{reading?'3D view':'List view'}</button></nav></header>
      {!reading&&<main id="top" className={`field-shell ${panel!==null?'has-panel':''}`}>
        <Scene selected={panel==='about'?9:typeof panel==='number'?panel:null} blocked={panel!==null} follow={follow} motion={motion} running={running} input={input} command={command} onOpen={openProject} onNearest={setNearest} onScore={setScore} onReady={()=>setReady(true)}/>
        <div className="field-intro"><p>CS @ UNIVERSITY OF MICHIGAN</p><h1>Ethan Moon.</h1><span>Lead Full-Stack Engineer, Ody<br/>Robotics researcher, U-M iRaL</span></div>
        <div className="field-caption"><span className="field-caption-dot"/>PROJECTS ON THE CONCOURSE</div>
        <div className="field-toolbar"><button aria-label={follow?'Full stadium':'Follow ball'} onClick={()=>setFollow(v=>!v)} aria-pressed={follow}>{follow?<Map size={16}/>:<LocateFixed size={16}/>}<span>{follow?'Full stadium':'Follow ball'}</span></button><button aria-label="Reset ball" onClick={()=>send('reset')}><RotateCcw size={16}/><span>Reset ball</span></button><button aria-label={motion?'Less motion':'More motion'} onClick={()=>setMotion(v=>!v)} aria-pressed={!motion}>{motion?<Pause size={16}/>:<Play size={16}/>}<span>{motion?'Less motion':'More motion'}</span></button></div>
        {nearest!==null&&<button className="nearby-project" onClick={()=>openProject(nearest)}><span>{exhibits[nearest].name}</span><span>{nearest===9?'About me':'Open project'} <CornerDownLeft size={14}/></span></button>}
        <div className="field-bottom"><div className="field-controls"><div className="key-guide"><span className="key-cluster"><kbd>W</kbd><span><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span></span><div><strong>Move the ball</strong><span>Arrow keys also work · Space to kick</span></div></div><p><Move size={13}/> Drag to rotate · Scroll to zoom · Click grass to move</p></div><div className="field-status"><span>{ready?'STADIUM OPEN':'LOADING'}</span><strong aria-live="polite" aria-atomic="true">{String(score).padStart(2,'0')}<small> GOALS</small></strong></div></div>
        <div className="touch-controls" aria-label="Ball controls">{[{label:'Move up',x:0,z:-1,Icon:ArrowUp},{label:'Move left',x:-1,z:0,Icon:ArrowLeft},{label:'Move down',x:0,z:1,Icon:ArrowDown},{label:'Move right',x:1,z:0,Icon:ArrowRight}].map(({label,x,z,Icon})=><button key={label} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current={x,z};}} onPointerUp={()=>{input.current={x:0,z:0};}} onPointerCancel={()=>{input.current={x:0,z:0};}} onLostPointerCapture={()=>{input.current={x:0,z:0};}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.current={x,z};}}} onKeyUp={()=>{input.current={x:0,z:0};}} onBlur={()=>{input.current={x:0,z:0};}}><Icon size={19}/></button>)}<button className="kick-button" onClick={()=>send('kick')}>Kick</button></div>
        <div className="field-socials"><a href="https://github.com/emoon0108" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/ethan-moon0108/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="mailto:ethmoon@umich.edu">Email ↗</a></div>
      </main>}
      <div className={`reading-view ${reading?'is-open':''}`}>{children}</div>
    </div>
    <dialog ref={dialog} className="portfolio-dialog" onClose={()=>setPanel(null)} onClick={e=>{if(e.target===dialog.current){const rect=dialog.current.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)setPanel(null);}}} aria-labelledby="panel-title">
      <button className="dialog-close" onClick={()=>setPanel(null)} aria-label="Close panel"><X size={19}/></button>
      {project?<><p className="panel-kicker">{String((panel as number)+1).padStart(2,'0')} / {project.year}</p><h2 id="panel-title">{project.name}</h2><span className="panel-role">{project.category}</span><h3>{project.summary}</h3><p>{project.detail}</p><p className="panel-note">{project.note}</p><p className="panel-tech">{project.tech.join(' / ')}</p><div className="project-links">{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noreferrer">{project.linkLabel}<ArrowUpRight size={15}/></a>}{project.codeUrl&&<a href={project.codeUrl} target="_blank" rel="noreferrer">Source code<ArrowUpRight size={15}/></a>}</div><button className="project-animation" onClick={()=>setRunning(v=>!v)} aria-pressed={running}>{running?<Pause size={14}/>:<Play size={14}/>} {running?project.actionDone:project.action}</button><div className="panel-pagination"><button onClick={()=>openProject(((panel as number)+exhibits.length-1)%exhibits.length)}>← Previous</button><button onClick={()=>openProject(((panel as number)+1)%exhibits.length)}>Next →</button></div></>:panel==='projects'?<><p className="panel-kicker">PROJECTS & RESEARCH</p><h2 id="panel-title">Project index</h2><div className="panel-index">{exhibits.map((p,i)=><button key={p.id} onClick={()=>openProject(i)}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{p.name}</strong><small>{i===9?'Background & contact':projects[i].category}</small></div><ArrowUpRight size={16}/></button>)}</div></>:<><p className="panel-kicker">10 / ABOUT ME</p><h2 id="panel-title">Ethan Moon</h2><Image className="about-portrait" src="/ethan-portrait.jpg" alt="Ethan Moon" width={480} height={640} sizes="(max-width:700px) 80vw, 350px"/><p>I’m a computer science student at the University of Michigan College of Engineering, with a minor in math. I work on backend systems, applied AI, and simulation.</p><p>I lead full-stack engineering and the U.S. team at Ody. At Michigan’s iRaL, I research vision-language navigation for drones. I also work with GVSU collaborators on bioprinting simulation and research papers.</p><p className="panel-note">B.S.E. Computer Science · Expected May 2028</p><div className="panel-pagination"><button onClick={()=>openProject(8)}>← Flight & orbits</button><button onClick={()=>openProject(0)}>NoSpoilers →</button></div><div className="about-history">{timeline.map(t=><div key={t.title}><small>{t.year}</small><h3>{t.title}</h3></div>)}</div><div className="project-links"><a href="mailto:ethmoon@umich.edu">Email<ArrowUpRight size={15}/></a><a href="/Ethan_Moon_Resume.pdf" target="_blank" rel="noreferrer">Résumé<ArrowUpRight size={15}/></a></div></>}
    </dialog>
  </>;
}
